
language: objective-c
osx_image: xcode61
script:
    - xctool -workspace SwiftBitmask.xcworkspace -scheme SwiftBitmask build test
    # - xctool -workspace SwiftBitmask.xcworkspace -scheme SwiftBitmask_iOS -sdk iphonesimulator build test


# language: objective-c
#
# script:
#   - bundle exec rake default