
language: objective-c
osx_image: xcode63
script:
    - xctool build test
    # - xctool -workspace SwiftBitmask.xcworkspace -scheme SwiftBitmask build test
    # - xctool -workspace SwiftBitmask.xcworkspace -scheme SwiftBitmask_iOS -sdk iphonesimulator build test


